#!/bin/zsh


# Getting the filename (which is the task name) from the argument, or exit
case $1 in 
    "" ) 
        echo "You need to specify a name. Try again"
        exit;;
    *.py ) 
        filename=${1:0:-3};;
    * ) 
        filename=$1;;
esac

# Creating the file
touch $filename.py
echo "* file $filename.py created"

# Adding a header to the file
echo "from typing import List

# The essence of the task
TASK = \"\"\"

\"\"\"


class Solution:
    
" >> $filename.py

# Asking if test folder is needed and creating it 
if [[ ! -e ./tests ]]; 
then 
    printf "* tests directory doesn't exist. Create one? "
    read answer
    
    if grep -iq 'y\|yes' <<< $answer
    then
        mkdir ./tests
        touch ./tests/__init__.py
        echo '* tests directory with __init__.py file created'
    else
        echo '* Skipping tests.'
        exit;
    fi
else
    echo "* tests directory already exists"
fi

# Creating file for testing in test directory
testfile=tests/test_$filename.py
touch $testfile
echo "* $testfile created"

# Reformatting from snake_case to PascalCase
classname=$( sed -E 's/[-_](.)|^(.)/\u\1\2/g' <<< $filename )

# Adding header to the test file
echo "import unittest
from ..$filename import Solution


class $classname""TestCase(unittest.TestCase):

    def setUp(self) -> None:
        self.sol = Solution().
        return super().setUp()

    def test1(self):
        args = {
            'nums':
        }
        expected_answer =

        res = self.sol(**args)
        assert res == expected_answer
" >> $testfile